version: "3.8"

services:
  api:
    build: .
    container_name: marketplace_api
    ports:
      - "4015:4015"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=4015
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
